### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by codevea** [monsieurbiz/SyliusHomepagePlugin#48]
Hello!
Installation error:
sylius version 2.0.7 / symfony 7.2 / Php 8.3
Do you have any information about this type of error during installation?
Bonjour, Avez-vous des informations sur ce type d'erreur lors de l'installation ?
Thank you!

![Image](https://github.com/user-attachments/assets/b1fa20be-a023-428f-ac11-abc7aa3ddf1c)

```
composer require monsieurbiz/sylius-homepage-plugin
./composer.json has been updated
Running composer update monsieurbiz/sylius-homepage-plugin
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package behat/transliterator is abandoned, you should avoid using it. No replacement was suggested.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
155 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
  - Skipping recipe for nyholm/psr7: all versions of the recipe conflict with your package versions.

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!   // Clearing the cache for the dev environment with debug true
!!
!!
!!  In FileLoader.php line 177:
!!                                                                                                                                                    
                                                                                                                                                      
!!    Unable to find file "@MonsieurBizSyliusMediaManagerPlugin/Resources/config/config.yaml" in @MonsieurBizSyliusMediaManagerPlugin/Resources/config/                                                                                                                                                     
!!    config.yaml (which is being imported from "C:\Users\natha\OneDrive\Documents\www\laBoutique/config/packages/monsieurbiz_media_manager_plugin.yaml                                                                                                                                                     
!!    "). Make sure the "MonsieurBizSyliusMediaManagerPlugin/Resources/config/config.yaml" bundle is correctly registered and loaded in the application                                                                                                                                                     
!!     kernel class. If the bundle is registered, make sure the bundle path "@MonsieurBizSyliusMediaManagerPlugin/Resources/config/config.yaml" is not                                                                                                                                                      
!!    empty.                                                                                                                                          
                                                                                                                                                      
!!                                                                                                                                                    
                                                                                                                                                      
!!
!!  In Kernel.php line 231:
!!  
!!    Unable to find file "@MonsieurBizSyliusMediaManagerPlugin/Resources/config/config.yaml".  
!!  
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!
!!
Script @auto-scripts was called via post-update-cmd
```



```
imports:
    - { resource: "@MonsieurBizSyliusHomepagePlugin/Resources/config/config.yaml" }
```

```

monsieurbiz_sylius_homepage_admin:
    resource: "@MonsieurBizSyliusHomepagePlugin/Resources/config/routes/admin.yaml"
    prefix: /%sylius_admin.path_name%

monsieurbiz_sylius_homepage_homepage:
    path: /{_locale}/
    methods: [GET]
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
    defaults:
        _controller: monsieurbiz_homepage.controller.homepage::indexAction
        _sylius:
            template: '@MonsieurBizSyliusHomepagePlugin/Homepage/index.html.twig'
            repository:
                method: findOneByChannelAndLocale
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"

```
